# Generated by Django 4.1.1 on 2022-11-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_discord_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
