# Generated by Django 4.1.1 on 2022-11-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0043_remove_coach_accomplishments'),
        ('users', '0008_accomplishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coaches.coach'),
        ),
    ]
