# Generated by Django 4.1.1 on 2022-11-18 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_accomplishment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
