# Generated by Django 4.1.1 on 2022-11-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_accomplishment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
