# Generated by Django 4.1.1 on 2022-11-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_accomplishment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accomplishment',
        ),
    ]
