# Generated by Django 4.1.1 on 2022-12-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='division',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('', '')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master Tier', 'Master Tier'), ('Grandmaster', 'Grandmaster'), ('Challenger', 'Challenger'), ('UNRANKED', 'UNRANKED')], default='UNRANKED', max_length=50),
        ),
    ]
