# Generated by Django 4.1.7 on 2023-04-17 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_remove_message_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
