# Generated by Django 4.1.7 on 2024-02-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_alter_profile_is_coach"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created_date",
            field=models.DateTimeField(auto_created=True),
        ),
    ]
