# Generated by Django 4.1.7 on 2024-02-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_alter_message_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
