# Generated by Django 4.1.7 on 2024-02-14 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_alter_message_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
