# Generated by Django 4.1.1 on 2022-10-12 19:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
                ('rating_total', models.IntegerField(blank=True, default=0, null=True)),
                ('rating_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('rating_value', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaches.coach')),
            ],
        ),
    ]
