# Generated by Django 4.1.1 on 2022-10-02 01:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('name', models.TextField(max_length=35, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('body', models.TextField(blank=True, max_length=5000)),
                ('user_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaches.coach')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='reviews',
            field=models.ManyToManyField(to='coaches.review'),
        ),
    ]
