# Generated by Django 4.1.1 on 2022-10-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rank', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Plat', 'Platinum'), ('Diamond', 'Diamond'), ('Master', 'Master Tier'), ('GM', 'Grandmaster'), ('Chall', 'Challenger')], max_length=100)),
                ('current_division', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('', '')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='rank',
            field=models.ManyToManyField(blank=True, to='coaches.rank'),
        ),
    ]
