# Generated by Django 4.1.1 on 2022-10-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_rank_coach_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='current_division',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('', '')], max_length=50),
        ),
    ]
