# Generated by Django 4.1.1 on 2022-10-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_alter_rank_current_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='rank',
        ),
        migrations.AddField(
            model_name='rank',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coaches.coach'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='current_division',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('', '')], default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='rank',
            name='current_rank',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Plat', 'Platinum'), ('Diamond', 'Diamond'), ('Master', 'Master Tier'), ('GM', 'Grandmaster'), ('Chall', 'Challenger')], default='UNRANKED', max_length=100),
        ),
    ]
