# Generated by Django 4.1.1 on 2022-10-16 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0006_remove_rank_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coaches.coach'),
        ),
    ]
