# Generated by Django 4.1.1 on 2022-10-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0007_rank_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rank',
        ),
        migrations.AddField(
            model_name='coach',
            name='rank',
            field=models.ManyToManyField(blank=True, to='coaches.rank'),
        ),
    ]
