# Generated by Django 4.1.1 on 2022-10-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0009_alter_rank_current_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='profile_img',
            field=models.ImageField(default='images/BG_logo.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='rank',
            name='current_rank',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master', 'Master Tier'), ('Grandmaster', 'Grandmaster'), ('Challenger', 'Challenger')], default='UNRANKED', max_length=100),
        ),
    ]
