# Generated by Django 4.1.1 on 2022-10-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0010_coach_profile_img_alter_rank_current_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='profile_img',
            field=models.ImageField(default='static/images/Posters_Pic.jpg', null=True, upload_to=''),
        ),
    ]
