# Generated by Django 4.1.1 on 2022-10-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0011_alter_coach_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='profile_img',
            field=models.ImageField(default='/BG_logo.jpg', null=True, upload_to=''),
        ),
    ]
