# Generated by Django 4.1.1 on 2022-11-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0025_coach_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='owner',
        ),
    ]
