# Generated by Django 4.1.1 on 2022-11-10 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_user'),
        ('coaches', '0026_remove_coach_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
