# Generated by Django 4.1.1 on 2022-11-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0027_coach_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='discord_link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
