# Generated by Django 4.1.1 on 2022-11-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0028_coach_discord_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='discord_link',
        ),
    ]
