# Generated by Django 4.1.1 on 2022-11-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0029_remove_coach_discord_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='accomplishments',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
