# Generated by Django 4.1.1 on 2022-11-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0030_coach_accomplishments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='owner',
            new_name='user_type',
        ),
    ]
