# Generated by Django 4.1.1 on 2022-11-15 20:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0031_rename_owner_coach_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='rank',
        ),
        migrations.AlterField(
            model_name='rank',
            name='current_rank',
            field=models.CharField(choices=[('1', 'Bronze'), ('2', 'Silver'), ('3', 'Gold'), ('4', 'Platinum'), ('5', 'Diamond'), ('6', 'Master Tier'), ('7', 'Grandmaster'), ('8', 'Challenger'), ('9', 'UNRANKED')], default='UNRANKED', max_length=100),
        ),
        migrations.AlterField(
            model_name='rank',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='rank',
            field=models.OneToOneField(blank=True, choices=[('1', 'Bronze'), ('2', 'Silver'), ('3', 'Gold'), ('4', 'Platinum'), ('5', 'Diamond'), ('6', 'Master Tier'), ('7', 'Grandmaster'), ('8', 'Challenger'), ('9', 'UNRANKED')], null=True, on_delete=django.db.models.deletion.CASCADE, to='coaches.rank'),
        ),
    ]
