# Generated by Django 4.1.1 on 2022-11-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0032_remove_coach_rank_alter_rank_current_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='rank',
            field=models.OneToOneField(blank=True, choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master Tier', 'Master Tier'), ('Grandmaster', 'Grandmaster'), ('Challenger', 'Challenger'), ('UNRANKED', 'UNRANKED')], null=True, on_delete=django.db.models.deletion.CASCADE, to='coaches.rank'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='current_rank',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master Tier', 'Master Tier'), ('Grandmaster', 'Grandmaster'), ('Challenger', 'Challenger'), ('UNRANKED', 'UNRANKED')], default='UNRANKED', max_length=100),
        ),
    ]
