# Generated by Django 4.1.1 on 2022-11-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0034_alter_rank_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='rank',
        ),
    ]
