# Generated by Django 4.1.1 on 2022-11-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0036_coach_rank_alter_rank_current_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaches.rank'),
        ),
    ]
