# Generated by Django 4.1.1 on 2022-11-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0038_alter_rank_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='rank',
        ),
        migrations.AddField(
            model_name='coach',
            name='rank',
            field=models.ManyToManyField(blank=True, to='coaches.rank'),
        ),
    ]
