# Generated by Django 4.1.1 on 2022-11-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0039_remove_coach_rank_coach_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='current_division',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='current_rank',
        ),
    ]
