# Generated by Django 4.1.1 on 2022-11-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0040_remove_rank_current_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='current_division',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('', '')], default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='rank',
            name='current_rank',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master Tier', 'Master Tier'), ('Grandmaster', 'Grandmaster'), ('Challenger', 'Challenger'), ('UNRANKED', 'UNRANKED')], default='8', max_length=100),
        ),
    ]
