# Generated by Django 4.1.1 on 2022-11-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0042_alter_rank_current_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='accomplishments',
        ),
    ]
