# Generated by Django 4.1.1 on 2022-11-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0044_accomplishments'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='headline',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
