# Generated by Django 4.1.1 on 2022-12-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0045_coach_headline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='name',
            new_name='display_name',
        ),
    ]
