# Generated by Django 4.1.1 on 2022-12-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0047_coach_discord_link_alter_coach_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='discord_link',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
