# Generated by Django 4.1.1 on 2022-12-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0048_alter_coach_discord_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='rank',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
