# Generated by Django 4.1.1 on 2023-01-09 21:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0050_review_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_value',
            field=models.CharField(choices=[('Up', 'Up Vote'), ('Down', 'Down Vote')], max_length=200),
        ),
    ]
