# Generated by Django 4.1.1 on 2023-01-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0054_alter_review_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating_value',
            field=models.CharField(choices=[('1.0', '5'), ('0.9', '4.5'), ('0.8', '4.0'), ('0.7', '3.5'), ('0.6', '3.0'), ('0.5', '2.5'), ('0.4', '2.0'), ('0.3', '1.5'), ('0.2', '1.0'), ('0.1', '0.5'), ('0', '0')], max_length=200),
        ),
    ]
