# Generated by Django 4.1.1 on 2023-01-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0058_alter_review_rating_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_date']},
        ),
    ]
