# Generated by Django 4.1.7 on 2024-02-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coaches", "0066_alter_review_owner_alter_review_rating_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
